---
- name: Creacion de usuarios con sus respectivos grupos
  hosts: servers
  become: true
  no_log: false

  #vars_files inclue archivos externos de variables
  vars_files:
    - hash_dictionary_vars.yml

  tasks:
    - name: Asegurese que los grupos del play sean creados
      loop: "{{ mygroups }}"
      ansible.builtin.group:
        name: "{{ item }}"
        state: present


    - name: Asegurese que los usuarios se creen con sus respectivos valores 
      #dict2items es un filtro para convertir un diccionario en lista de elementos clave valor
      loop: "{{ myusers | dict2items }}"
      ansible.builtin.user: 
        name: "{{ item['key'] }}"
        state: present
        groups: "{{ item['value']['groups'] }}"
        password: "{{ item['value']['password'] | password_hash('sha512') }}"
        update_password: on_create
        generate_ssh_key: true

