---
- name: manage rocky 9 servers iusing include tasks
  hosts: servers
  gather_facts: yes

  tasks:
    - name: Include web server tasks for rocky 9
      include_tasks: webserver-tasks.yml
      ansible_distribution_major_version = "9"

    - name: Include firewall tasks for rocky 9
      include_tasks: firewall-tasks.yml
      ansible_distribution_major_version = "9"

