---
- name: manage rocky 9 servers using import tasks
  hosts: rocky_servers
  gather_facts: yes
  become: true
  vars_files:
    - sudo_pwd.yml

  tasks:
    - name: import webserver tasks for rocky 9
      import_tasks: webserver-tasks.yml
      when: ansible_distribution_major_version == "9"

    - name: import firewall tasks for rocky 9
      import_tasks: firewall-tasks.yml
      when: ansible_distribution_major_version == "9"


