---
- name: manage Rocky 9 servers using include tasks
  hosts: servers
  gather_facts: yes
  tasks:

    - name: Force facts recollection
      setup:
      when: ansible_facts is undefined

    - name: Include web server tasks for rocky 9
      include_tasks: webserver-tasks.yml
      when: ansible_distribution_major_version == "9"

    - name: Include firewall tasks for rocky 9
      include_tasks: firewall-tasks.yml
      when: ansible_distribution_major_version == "9"

