- name: Install Nginx on rocky 9
  ansible.builtin.dnf:
    name: nginx
    state: present


- name: Start and enable NGINX service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
